INSERT INTO question (category, difficulty, option1, option2, option3, question_text, correct_answer)
VALUES
    ('Java', 'Easy', '4 bytes', '2 bytes', '8 bytes', 'What is the size of int in Java?', '4 bytes'),
    ('Python', 'Medium', 'def', 'function', 'lambda', 'Which keyword is used to define a function in Python?', 'def'),
    ('TypeScript', 'Hard', 'Type annotations', 'Syntax', 'Compilation', 'What is the main difference between TypeScript and JavaScript?', 'Type annotations'),
    ('Java', 'Easy', 'start()', 'run()', 'begin()', 'Which method is used to start a thread in Java?', 'start()'),
    ('Python', 'Medium', 'virtualenv', 'venv', 'env', 'How do you create a virtual environment in Python?', 'venv'),
    ('TypeScript', 'Hard', 'interface', 'type', 'class', 'How do you define an interface in TypeScript?', 'interface'),
    ('Java', 'Easy', 'true', 'false', 'null', 'What is the default value of a boolean in Java?', 'false'),
    ('Python', 'Medium', 'pandas', 'numpy', 'matplotlib', 'Which library is used for data manipulation in Python?', 'pandas'),
    ('TypeScript', 'Hard', 'To make properties immutable', 'To define constants', 'To create readonly variables', 'What is the purpose of the "readonly" modifier in TypeScript?', 'To make properties immutable'),
    ('Java', 'Easy', 'java.util', 'java.lang', 'java.io', 'Which package contains the Random class in Java?', 'java.util'),
    ('Python', 'Medium', 'try-except', 'try-catch', 'try-finally', 'How do you handle exceptions in Python?', 'try-except'),
    ('TypeScript', 'Hard', 'To represent values that never occur', 'To define infinite loops', 'To create unending functions', 'What is the use of the "never" type in TypeScript?', 'To represent values that never occur'),
    ('Java', 'Easy', 'Object', 'Class', 'Base', 'What is the parent class of all classes in Java?', 'Object'),
    ('Python', 'Medium', 'pip install', 'python install', 'install package', 'How do you install a package in Python?', 'pip install'),
    ('TypeScript', 'Hard', 'tuple', 'array', 'list', 'How do you declare a tuple in TypeScript?', 'tuple'),
    ('Java', 'Easy', '.class', '.java', '.byte', 'What is the extension of Java bytecode files?', '.class'),
    ('Python', 'Medium', 'len()', 'size()', 'length()', 'Which function is used to get the length of a list in Python?', 'len()'),
    ('TypeScript', 'Hard', 'To define abstract methods', 'To create abstract classes', 'To implement interfaces', 'What is the purpose of the "abstract" class in TypeScript?', 'To define abstract methods'),
    ('Java', 'Easy', 'extends', 'implements', 'inherits', 'Which keyword is used to inherit a class in Java?', 'extends'),
    ('Python', 'Medium', '{key: value}', '[key: value]', '(key, value)', 'How do you create a dictionary in Python?', '{key: value}');